# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN.xci
# IP: The module: 'fifo_generator_ORN' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN/fifo_generator_ORN.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_ORN'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_ORN'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN.xci
# IP: The module: 'fifo_generator_ORN' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN/fifo_generator_ORN.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_ORN'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_ORN'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
