# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.cache/wt [current_project]
set_property parent.project_path D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:cmod_a7-35t:part0:1.1 [current_project]
set_property ip_repo_paths d:/research/Desktop/Cmod-A7-35T-GPIO/repo [current_project]
set_property ip_output_repo d:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN.xci
set_property is_locked true [get_files D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.runs/fifo_generator_ORN_synth_1 -new_name fifo_generator_ORN -ip [get_ips fifo_generator_ORN]]

if { $cached_ip eq {} } {

synth_design -top fifo_generator_ORN -part xc7a35tcpg236-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix fifo_generator_ORN_ fifo_generator_ORN.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fifo_generator_ORN_stub.v
 lappend ipCachedFiles fifo_generator_ORN_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fifo_generator_ORN_stub.vhdl
 lappend ipCachedFiles fifo_generator_ORN_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fifo_generator_ORN_sim_netlist.v
 lappend ipCachedFiles fifo_generator_ORN_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fifo_generator_ORN_sim_netlist.vhdl
 lappend ipCachedFiles fifo_generator_ORN_sim_netlist.vhdl

 config_ip_cache -add -dcp fifo_generator_ORN.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips fifo_generator_ORN]
}

rename_ref -prefix_all fifo_generator_ORN_

write_checkpoint -force -noxdef fifo_generator_ORN.dcp

catch { report_utilization -file fifo_generator_ORN_utilization_synth.rpt -pb fifo_generator_ORN_utilization_synth.pb }

if { [catch {
  file copy -force D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.runs/fifo_generator_ORN_synth_1/fifo_generator_ORN.dcp D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.runs/fifo_generator_ORN_synth_1/fifo_generator_ORN.dcp D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.runs/fifo_generator_ORN_synth_1/fifo_generator_ORN_stub.v D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.runs/fifo_generator_ORN_synth_1/fifo_generator_ORN_stub.vhdl D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.runs/fifo_generator_ORN_synth_1/fifo_generator_ORN_sim_netlist.v D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.runs/fifo_generator_ORN_synth_1/fifo_generator_ORN_sim_netlist.vhdl D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.ip_user_files/ip/fifo_generator_ORN]} {
  catch { 
    file copy -force D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN_stub.v D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.ip_user_files/ip/fifo_generator_ORN
  }
}

if {[file isdir D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.ip_user_files/ip/fifo_generator_ORN]} {
  catch { 
    file copy -force D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN_stub.vhdl D:/research/Xilinx/DrosophilaOlfactorySystem_MBON_20210912/DrosophilaOlfactorySystem_MBON_20210912.ip_user_files/ip/fifo_generator_ORN
  }
}
