# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/FlyOlfactoryNetwork/FlyOlfactoryNetwork.srcs/sources_1/ip/blk_mem_weight_PNKC_1/blk_mem_weight_PNKC_1.xci
# IP: The module: 'blk_mem_weight_PNKC_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/FlyOlfactoryNetwork/FlyOlfactoryNetwork.srcs/sources_1/ip/blk_mem_weight_PNKC_1/blk_mem_weight_PNKC_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_weight_PNKC_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/FlyOlfactoryNetwork/FlyOlfactoryNetwork.srcs/sources_1/ip/blk_mem_weight_PNKC_1/blk_mem_weight_PNKC_1.xci
# IP: The module: 'blk_mem_weight_PNKC_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/FlyOlfactoryNetwork/FlyOlfactoryNetwork.srcs/sources_1/ip/blk_mem_weight_PNKC_1/blk_mem_weight_PNKC_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_weight_PNKC_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
