# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/research/Xilinx/DrosophilaOlfactorySystem20210701/DrosophilaOlfactorySystem20210701.srcs/sources_1/ip/dssn_glomeruli_fifo/dssn_glomeruli_fifo.xci
# IP: The module: 'dssn_glomeruli_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/research/Xilinx/DrosophilaOlfactorySystem20210701/DrosophilaOlfactorySystem20210701.srcs/sources_1/ip/dssn_glomeruli_fifo/dssn_glomeruli_fifo/dssn_glomeruli_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'dssn_glomeruli_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/research/Xilinx/DrosophilaOlfactorySystem20210701/DrosophilaOlfactorySystem20210701.srcs/sources_1/ip/dssn_glomeruli_fifo/dssn_glomeruli_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dssn_glomeruli_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/research/Xilinx/DrosophilaOlfactorySystem20210701/DrosophilaOlfactorySystem20210701.srcs/sources_1/ip/dssn_glomeruli_fifo/dssn_glomeruli_fifo.xci
# IP: The module: 'dssn_glomeruli_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/research/Xilinx/DrosophilaOlfactorySystem20210701/DrosophilaOlfactorySystem20210701.srcs/sources_1/ip/dssn_glomeruli_fifo/dssn_glomeruli_fifo/dssn_glomeruli_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'dssn_glomeruli_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/research/Xilinx/DrosophilaOlfactorySystem20210701/DrosophilaOlfactorySystem20210701.srcs/sources_1/ip/dssn_glomeruli_fifo/dssn_glomeruli_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dssn_glomeruli_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
