# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/research/Xilinx/DrosophilaOlfactorySystem20201127/DrosophilaOlfactorySystem20201127.srcs/sources_1/ip/blk_mem_q/blk_mem_q.xci
# IP: The module: 'blk_mem_q' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/research/Xilinx/DrosophilaOlfactorySystem20201127/DrosophilaOlfactorySystem20201127.srcs/sources_1/ip/blk_mem_q/blk_mem_q_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_q'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/research/Xilinx/DrosophilaOlfactorySystem20201127/DrosophilaOlfactorySystem20201127.srcs/sources_1/ip/blk_mem_q/blk_mem_q.xci
# IP: The module: 'blk_mem_q' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/research/Xilinx/DrosophilaOlfactorySystem20201127/DrosophilaOlfactorySystem20201127.srcs/sources_1/ip/blk_mem_q/blk_mem_q_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_q'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
