# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/DrosophilaOlfactorySystem20230324.srcs/sources_1/ip/blk_mem_LNPN_I_exci/blk_mem_LNPN_I_exci.xci
# IP: The module: 'blk_mem_LNPN_I_exci' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/DrosophilaOlfactorySystem20230324.srcs/sources_1/ip/blk_mem_LNPN_I_exci/blk_mem_LNPN_I_exci_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_LNPN_I_exci'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/DrosophilaOlfactorySystem20230324.srcs/sources_1/ip/blk_mem_LNPN_I_exci/blk_mem_LNPN_I_exci.xci
# IP: The module: 'blk_mem_LNPN_I_exci' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/DrosophilaOlfactorySystem20230324.srcs/sources_1/ip/blk_mem_LNPN_I_exci/blk_mem_LNPN_I_exci_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_LNPN_I_exci'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
