# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.cache/wt [current_project]
set_property parent.project_path D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:cmod_a7-35t:part0:1.1 [current_project]
set_property ip_repo_paths d:/research/Desktop/Cmod-A7-35T-GPIO/repo [current_project]
set_property ip_output_repo d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/blk_mem_gen_ORN_sc/blk_mem_gen_ORN_sc.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/blk_mem_gen_ORN_sc/blk_mem_gen_ORN_sc.dcp]
add_files -quiet d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/fifo_generator_ORN/fifo_generator_ORN.dcp]
add_files -quiet d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/dssn_glomeruli_fifo/dssn_glomeruli_fifo.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/dssn_glomeruli_fifo/dssn_glomeruli_fifo.dcp]
add_files -quiet d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/blk_mem_n/blk_mem_n.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/blk_mem_n/blk_mem_n.dcp]
add_files -quiet d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/blk_mem_q/blk_mem_q.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/blk_mem_q/blk_mem_q.dcp]
add_files -quiet d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/blk_mem_u/blk_mem_u.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/blk_mem_u/blk_mem_u.dcp]
add_files -quiet d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/blk_mem_fc/blk_mem_fc.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/blk_mem_fc/blk_mem_fc.dcp]
read_vhdl -library xil_defaultlib {
  D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/new/DSSN_PN.vhd
  D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/new/DSSN_NP2426_class1.vhd
  D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/new/DSSN_NP1227_class1.vhd
  D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/new/DSSN_MBON.vhd
  D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/new/DSSN_Krasavietz_class2.vhd
  D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/new/DSSN_KC.vhd
  D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/new/DSSN_CREPINE.vhd
  D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/new/DSSN_APL.vhd
  D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/new/DSSN_Krasavietz_class1.vhd
  D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/imports/hdl/UART_TX_CTRL.vhd
  D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/new/dssn_glomeruli_ctrl.vhd
  D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/new/UART_RX_CTRL.vhd
  D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/new/clk1_generator.vhd
  D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/new/clk1k_generator.vhd
  D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/new/blk_mem_ORN_ctrl.vhd
  D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/imports/hdl/GPIO.vhd
  D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/new/UART_TX_CTRL.vhd
}
read_ip -quiet D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

read_ip -quiet D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/blk_mem_v/blk_mem_v.xci
set_property used_in_implementation false [get_files -all d:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/blk_mem_v/blk_mem_v_ooc.xdc]
set_property is_locked true [get_files D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/sources_1/ip/blk_mem_v/blk_mem_v.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/constrs_1/imports/constraints/CmodA7_Master.xdc
set_property used_in_implementation false [get_files D:/research/Jupyter/github/fly-olfactory-network-fpga-main/vivado_projects/PQNtest/PQNtest.srcs/constrs_1/imports/constraints/CmodA7_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top GPIO_demo -part xc7a35tcpg236-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


write_checkpoint -force -noxdef GPIO_demo.dcp

catch { report_utilization -file GPIO_demo_utilization_synth.rpt -pb GPIO_demo_utilization_synth.pb }
