# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cmoda7.xdc

# IP: ip/blk_mem_q/blk_mem_q.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_q || ORIG_REF_NAME==blk_mem_q}]
