# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.cache/wt [current_project]
set_property parent.project_path D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:cmod_a7-35t:part0:1.1 [current_project]
set_property ip_output_repo d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/coe/weight_glomeruli_0.coe
add_files D:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/coe/weight_glomeruli_1.coe
add_files D:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/coe/weight_glomeruli_2.coe
add_files D:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/coe/weight_glomeruli_3.coe
add_files D:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/coe/weight_glomeruli_4.coe
add_files D:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/coe/weight_glomeruli_5.coe
add_files D:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/coe/weight_glomeruli_6.coe
add_files D:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/coe/weight_KC_APLMBONa3_0.coe
add_files D:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/coe/weight_KC_MBONa1_0.coe
add_files D:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/coe/weight_PNKC_0.coe
add_files D:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/coe/weight_PNKC_1.coe
add_files D:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/coe/weight_PNKC_2.coe
add_files D:/research/Jupyter/DrorsophilaOlfactorySystem/release/coe/weight_glomeruli_0.coe
add_files D:/research/Jupyter/DrorsophilaOlfactorySystem/release/coe/weight_glomeruli_1.coe
add_files D:/research/Jupyter/DrorsophilaOlfactorySystem/release/coe/weight_glomeruli_2.coe
add_files D:/research/Jupyter/DrorsophilaOlfactorySystem/release/coe/weight_glomeruli_3.coe
add_files D:/research/Jupyter/DrorsophilaOlfactorySystem/release/coe/weight_glomeruli_4.coe
add_files D:/research/Jupyter/DrorsophilaOlfactorySystem/release/coe/weight_glomeruli_5.coe
add_files D:/research/Jupyter/DrorsophilaOlfactorySystem/release/coe/weight_glomeruli_6.coe
add_files D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/outputs/coe/weight_glomeruli_6.coe
add_files D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/outputs/coe/weight_glomeruli_5.coe
add_files D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/outputs/coe/weight_glomeruli_4.coe
add_files D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/outputs/coe/weight_glomeruli_3.coe
add_files D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/outputs/coe/weight_glomeruli_2.coe
add_files D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/outputs/coe/weight_glomeruli_1.coe
add_files D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/outputs/coe/weight_glomeruli_0.coe
add_files D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/outputs/coe/weight_KC_APLMBONa3_0.coe
add_files D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/outputs/coe/weight_KC_MBONa1_0.coe
add_files D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/outputs/coe/weight_PNKC_0.coe
add_files D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/outputs/coe/weight_PNKC_1.coe
add_files D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/outputs/coe/weight_PNKC_2.coe
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/clk_generator/clk_generator.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/clk_generator/clk_generator.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_v/blk_mem_v.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_v/blk_mem_v.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_n/blk_mem_n.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_n/blk_mem_n.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_u/blk_mem_u.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_u/blk_mem_u.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_fc/blk_mem_fc.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_fc/blk_mem_fc.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_glomeruli_0/blk_mem_weight_glomeruli_0.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_glomeruli_0/blk_mem_weight_glomeruli_0.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_glomeruli_1/blk_mem_weight_glomeruli_1.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_glomeruli_1/blk_mem_weight_glomeruli_1.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_glomeruli_2/blk_mem_weight_glomeruli_2.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_glomeruli_2/blk_mem_weight_glomeruli_2.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_PNKC_0/blk_mem_weight_PNKC_0.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_PNKC_0/blk_mem_weight_PNKC_0.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_LNPN_sc/blk_mem_LNPN_sc.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_LNPN_sc/blk_mem_LNPN_sc.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_KC_sc/blk_mem_KC_sc.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_KC_sc/blk_mem_KC_sc.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_KC_sr/blk_mem_KC_sr.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_KC_sr/blk_mem_KC_sr.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_KC_APLMBONa3/blk_mem_weight_KC_APLMBONa3.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_KC_APLMBONa3/blk_mem_weight_KC_APLMBONa3.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_KC_MBONa1/blk_mem_weight_KC_MBONa1.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_KC_MBONa1/blk_mem_weight_KC_MBONa1.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_glomeruli_5/blk_mem_weight_glomeruli_5.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_glomeruli_5/blk_mem_weight_glomeruli_5.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_LNPN_I_exci/blk_mem_LNPN_I_exci.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_LNPN_I_exci/blk_mem_LNPN_I_exci.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_ORN_sc/blk_mem_ORN_sc.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_ORN_sc/blk_mem_ORN_sc.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_glomeruli_6/blk_mem_weight_glomeruli_6.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_glomeruli_6/blk_mem_weight_glomeruli_6.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_LNPN_I_inhi/blk_mem_LNPN_I_inhi.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_LNPN_I_inhi/blk_mem_LNPN_I_inhi.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_glomeruli_3/blk_mem_weight_glomeruli_3.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_glomeruli_3/blk_mem_weight_glomeruli_3.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_PN_sc/blk_mem_PN_sc.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_PN_sc/blk_mem_PN_sc.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_KC_I/blk_mem_KC_I.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_KC_I/blk_mem_KC_I.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_glomeruli_4/blk_mem_weight_glomeruli_4.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_glomeruli_4/blk_mem_weight_glomeruli_4.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/fifo_txd/fifo_txd.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/fifo_txd/fifo_txd.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_PNKC_1/blk_mem_weight_PNKC_1.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_PNKC_1/blk_mem_weight_PNKC_1.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/fifo_rxd/fifo_rxd.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/fifo_rxd/fifo_rxd.dcp]
add_files -quiet d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_PNKC_2/blk_mem_weight_PNKC_2.dcp
set_property used_in_implementation false [get_files d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_weight_PNKC_2/blk_mem_weight_PNKC_2.dcp]
read_vhdl -library xil_defaultlib {
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/sc_accumulator_glomeruli.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/PQN_ON.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/PQN_KC.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/PQN_APL.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/PQN_PN.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/PQN_NP2446_class1.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/PQN_NP1227_class1.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/PQN_Krasaviets_class2.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/PQN_Krasaviets_class1.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/uart_txd_ctrl.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/uart_rxd_ctrl.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/sc_accumulator_PNKC.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/sc_accumulator_KC_APLMBON.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/PQN_MBON.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/sc_accumulator_KC_APLMBON_ctrl.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/sc_accumulator_PNKC_ctrl.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/sc_accumulator_glomeruli_ctrl.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/pqn_ctrl.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/fifo_txd_ctrl.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/fifo_rxd_ctrl.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/triger_generator.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/stdp_ctrl.vhd
  D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/new/main.vhd
}
read_ip -quiet D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_q/blk_mem_q.xci
set_property used_in_implementation false [get_files -all d:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_q/blk_mem_q_ooc.xdc]
set_property is_locked true [get_files D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/sources_1/ip/blk_mem_q/blk_mem_q.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/constrs_1/new/cmoda7.xdc
set_property used_in_implementation false [get_files D:/research/Jupyter/release/fly-olfactory-network-fpga/NeuralNetworks/code_and_data/vivado_projects/noAPL/noAPL.srcs/constrs_1/new/cmoda7.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top main -part xc7a35tcpg236-1


write_checkpoint -force -noxdef main.dcp

catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
