# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/DrosophilaOlfactorySystem20230324.srcs/sources_1/ip/clk_generator/clk_generator.xci
# IP: The module: 'clk_generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/DrosophilaOlfactorySystem20230324.srcs/sources_1/ip/clk_generator/clk_generator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_generator'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/DrosophilaOlfactorySystem20230324.srcs/sources_1/ip/clk_generator/clk_generator.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/DrosophilaOlfactorySystem20230324.srcs/sources_1/ip/clk_generator/clk_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: d:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/DrosophilaOlfactorySystem20230324.srcs/sources_1/ip/clk_generator/clk_generator.xci
# IP: The module: 'clk_generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/DrosophilaOlfactorySystem20230324.srcs/sources_1/ip/clk_generator/clk_generator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/DrosophilaOlfactorySystem20230324.srcs/sources_1/ip/clk_generator/clk_generator.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/research/Xilinx/DrosophilaOlfactorySystem/release/DrosophilaOlfactorySystem20230324/DrosophilaOlfactorySystem20230324.srcs/sources_1/ip/clk_generator/clk_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
